import type { Metadata } from "next";
import "./globals.css";
import { gilmerHeavy } from "@/src/utils/fonts";
import { Footer, Header } from "@/components/organisms";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={gilmerHeavy.variable}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
